export const BUSINESS_ENDPOINTS = {
  list: '/business',
  mine: '/business/me',
  detail: (id: string) => `/business/${id}`,
  submit: (id: string) => `/business/${id}/submit`,
  analytics: (id: string) => `/business/${id}/analytics`,
  campaigns: (id: string) => `/business/${id}/campaigns`,
  campaign: (id: string, campaignId: string) => `/business/${id}/campaigns/${campaignId}`,
  discounts: (id: string) => `/business/${id}/discounts`,
  discount: (id: string, discountId: string) => `/business/${id}/discounts/${discountId}`,
  members: (id: string) => `/business/${id}/members`,
  member: (id: string, userId: string) => `/business/${id}/members/${userId}`,
  memberRole: (id: string, userId: string) => `/business/${id}/members/${userId}/role`,
  services: (id: string) => `/business/${id}/services`,
  service: (id: string, serviceId: string) => `/business/${id}/services/${serviceId}`,
  products: (id: string) => `/business/${id}/products`,
  product: (id: string, productId: string) => `/business/${id}/products/${productId}`,
  billingStatus: (id: string) => `/payments/brand-status/${id}`,
  billingCheckout: '/payments/brand-checkout',
} as const
