export const ADMIN_ENDPOINTS = {
  stats: '/admin/stats',
  weeklyActivity: '/admin/activity/weekly',
  users: '/admin/users',
  user: (id: string) => `/admin/users/${id}`,
  userRole: (id: string) => `/admin/users/${id}/role`,
  userStatus: (id: string) => `/admin/users/${id}/status`,
  rides: '/admin/rides',
  ride: (id: string) => `/admin/rides/${id}`,
  rideStatus: (id: string) => `/admin/rides/${id}/status`,
  clubs: '/admin/clubs',
  club: (id: string) => `/admin/clubs/${id}`,
  clubVerify: (id: string) => `/admin/clubs/${id}/verify`,
  marketplace: '/admin/marketplace',
  listing: (id: string) => `/admin/marketplace/${id}`,
  listingStatus: (id: string) => `/admin/marketplace/${id}/status`,
  reports: '/admin/reports',
  report: (id: string) => `/admin/reports/${id}`,
  notifications: '/admin/notifications',
  settings: '/admin/settings',
  approvals: '/admin/approvals',
  businesses: '/admin/businesses',
  business: (id: string) => `/admin/businesses/${id}`,
  clubJoinRequestApprove: (id: string) => `/admin/club-join-requests/${id}/approve`,
  clubJoinRequestReject: (id: string) => `/admin/club-join-requests/${id}/reject`,
  rideParticipantAccept: (id: string) => `/admin/ride-participants/${id}/accept`,
  rideParticipantDecline: (id: string) => `/admin/ride-participants/${id}/decline`,
  adCampaigns: '/admin/ad-campaigns',
  adCampaignApprove: (id: string) => `/admin/ad-campaigns/${id}/approve`,
  adCampaignReject: (id: string) => `/admin/ad-campaigns/${id}/reject`,
  discounts: '/admin/discounts',
  discount: (id: string) => `/admin/discounts/${id}`,
  bulkVerifyClubs: '/admin/bulk/clubs/verify',
  bulkApproveClubRequests: '/admin/bulk/club-join-requests/approve',
  bulkAcceptRideParticipants: '/admin/bulk/ride-participants/accept',
  bulkApproveBusinesses: '/admin/bulk/businesses/approve',
  bulkApproveAdCampaigns: '/admin/bulk/ad-campaigns/approve',
  bulkAction: '/admin/bulk/action',
  /** Not under /admin — scoped bulk-action endpoints mounted at the API root. */
  clubManagerBulkAction: '/bulk/club-manager/action',
  brandManagerBulkAction: '/bulk/brand-manager/action',
} as const
